import './global.css'
import type { Metadata } from "next";
import Header from '@/components/layout/navbar/Header'
import Theme from "@/components/providers/Theme";
import { Container, CssBaseline } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <Header />
          <Container sx={{backgroundColor: 'primary.main', minHeight: '100vh'}}>
            <CssBaseline />
            {children}
          </Container>
        </Theme>
      </body>
    </html>
  );
}
