import './global.css'
import type { Metadata } from "next";
import Header from '@/components/layout/navbar/Header'
import Theme from "@/components/providers/Theme";
import { Container, CssBaseline } from "@mui/material";
import Sidebar from '@/components/layout/sidebar/Sidebar';
import StoreProvider from '@/components/providers/StoreProvider';
import PrerenderProductCategory from '@/components/products/PrerenderProductCategory';
import PrerenderAllProducts from '@/components/products/PrerenderAllProducts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <StoreProvider>

            <PrerenderProductCategory />
            <PrerenderAllProducts />

            <Header />
            <Container
              sx={{
                backgroundColor: 'primary.main',
                minHeight: '100vh',
                display: { mobile: 'flex' },
                paddingTop: 1
              }}
              maxWidth={false}
            >
              <CssBaseline />

              <Sidebar />
              {children}

            </Container>
          </StoreProvider>
        </Theme>
      </body>
    </html>
  );
}
